spring:
  application:
    name: e_commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        # ğŸ‘‡ (ì„ íƒ) PostgreSQL ì „ìš© ë°©ì–¸ ì„¤ì • (ì—†ì–´ë„ ë˜ì§€ë§Œ ë„£ìœ¼ë©´ ë” ì•ˆì •ì )
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: user
      password: 1234


external:
  product-service:
    url: http://localhost:8080
  order-service:
    url: http://localhost:8080

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentPurposeOnly12345}
  access-token-validity: 3600000
  refresh-token-validity: 604800000

ai:
  openai:
    api-key: ${OPENAI_API_KEY:dummy}
    base-url: https://api.openai.com
    model: gpt-4o-mini



logging:
  level:
    root: ERROR
    com.groom.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG

toss:
  payments:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY:}
    client-key: test_ck_AQ92ymxN349xlKM196KKVajRKXvd
    success-url: http://localhost:8080/pay-success.html
    fail-url: http://localhost:8080/pay-fail.html
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

server:
  port: 8081
