spring:
  application:
    name: e_commerce

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 20

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        # ğŸ‘‡ (ì„ íƒ) PostgreSQL ì „ìš© ë°©ì–¸ ì„¤ì • (ì—†ì–´ë„ ë˜ì§€ë§Œ ë„£ìœ¼ë©´ ë” ì•ˆì •ì )
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: user
      password: 1234

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  feign:
    circuitbreaker:
      enabled: true


external:
  product-service:
    url: http://localhost:8080
  order-service:
    url: http://localhost:8080

jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
  access-token-validity: 3600000
  refresh-token-validity: 604800000

ai:
  openai:
    api-key: ${OPENAI_API_KEY:dummy}
    base-url: https://api.openai.com
    model: gpt-4o-mini



logging:
  level:
    root: INFO
    com.groom.e_commerce: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

toss:
  payments:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY:}
    client-key: test_ck_AQ92ymxN349xlKM196KKVajRKXvd
    success-url: http://localhost:8080/pay-success.html
    fail-url: http://localhost:8080/pay-fail.html
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

# Resilienve4j ì •ì±… ì„¤ì • - ìˆ˜ì • í•„ìš”
resilience4j:
  circuitbreaker:
    instances:
      tossPaymentsClient:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5

  retry:
    instances:
      tossPaymentsClient:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - java.io.IOException
          - feign.RetryableException

  timelimiter:
    instances:
      tossPaymentsClient:
        timeoutDuration: 2s
